### ISSUE TITLE
来自 YukiHookAPI 原作者的一个小建议

### ISSUE THREAD

**Issue by fankes** [luckyzyx/luckyzyxtools#2]
1.可更新 API 到最新版本并开始使用 `YukiHookModulePrefs` 作为  XShare 共享数据存储，可参考 API 文档。
2. `configs ` 现可在 `onInit` 方法中装载，与 Hook 主体分离，否则会造成配置不生效的问题。
3.`README.md` 中的 API 拼写错误，不是 Yuku 是 Yuki。

若有其它建议与BUG欢迎向我反馈，感谢您的支持。

**Comment by luckyzyx** [comment]
诶嘿

**Comment by fankes** [comment]
> 诶嘿

嗯哈
